LLM_MODEL: google/gemma-3-270m
LLM_MODEL_PATH: google/gemma-3-270m
LLM_MAX_TOKENS: 384
LLM_API_DELAY: 0.1

CHUNK_SIZE: 800
CHUNK_OVERLAP: 160

N_ENTITY_DESCRIPTIONS: 2
N_QUERIES_PER_ENTITY: 2

SEARCH_METHOD: bm25
EMBEDDING_MODEL: null
TOP_K_SEARCH: 6
TOP_K_FINAL: 4

RANKING_ALGORITHM: bradley_terry
N_EXPERIMENTS: 2
EXPERIMENT_WINNERS: 2
EXPERIMENT_SUBSET_SIZE: 3

HIGH_CONFIDENCE_THRESHOLD: 0.8
LOW_CONFIDENCE_THRESHOLD: 0.3

DEFAULT_TIMEOUT: 30
LLM_TIMEOUT: 60
SEARCH_TIMEOUT: 10
RANKING_TIMEOUT: 30
EXPERIMENT_TIMEOUT: 30
ENTITY_DETECTION_TIMEOUT: 60
TOTAL_PROCESSING_TIMEOUT: 120
